/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_GL_TALLY_RECONListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_GL_TALLY_RECONList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZC_GL_TALLY_RECONList.onFilterBar().iCheckFilterField("Company Code");
            Then.onTheZC_GL_TALLY_RECONList.onFilterBar().iCheckFilterField("Current Period");
            Then.onTheZC_GL_TALLY_RECONList.onFilterBar().iCheckFilterField("Fiscal Year");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_GL_TALLY_RECONList.onTable().iCheckColumns(undefined, {"SAPCoCode":{"header":"Company Code"},"SAPGL":{"header":"Sap GL"},"CurrentPeriod":{"header":"Current Period"},"FiscalYear":{"header":"Fiscal Year"},"TallyGL":{"header":"Tally GL"},"CompanyCodeCurrency":{"header":"Currency"},"OpeningBalAtPeriodStart":{"header":"Opening Balance"},"DebitBal":{"header":"Debit Balance"},"CreditBal":{"header":"Credit Balance"},"CumulativeBalance":{"header":"Total Balance"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZC_GL_TALLY_RECONList.onFilterBar().iExecuteSearch();
            
            Then.onTheZC_GL_TALLY_RECONList.onTable().iCheckRows();

            When.onTheZC_GL_TALLY_RECONList.onTable().iPressRow(0);
            Then.onTheZC_GL_TALLY_RECONObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});